# Monokai-pro for Kitty
# Based on https://www.monokai.pro/

foreground            #f7f1ff
background            #2d2a2e
selection_foreground  #f7f1ff
selection_background  #525053
url_color             #78dce8
cursor #bab6c0
cursor_text_color #2d2a2e

active_tab_background #19181a
active_tab_foreground #ffd866
active_tab_font_style bold
inactive_tab_background #2d2a2e
inactive_tab_foreground #fcfcfa
inactive_tab_font_style normal
tab_fade 0.1 0.2 0.8 1
tab_bar_margin_width 1.0

dim_opacity 0.5
inactive_text_alpha 0.5
active_border_color #19181a
draw_minimal_borders yes
window_padding_width 10
window_margin_width 0
macos_titlebar_color background

# black
color0   #2d2a2e
color8   #727072

# red
color1   #fc618d
color9   #FF5C57

# green
color2   #7bd88f
color10  #a9dc76

# yellow
color3   #fce566
color11  #ffd866

# blue
color4  #fd9353
color12 #3399cc

# magenta
color5   #948ae3
color13  #ff6188

# cyan
color6   #5ad4e6
color14  #78dce8

# white
color7   #f7f1ff
color15  #fcfcfa
